# Generated by Django 3.0.2 on 2020-01-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('fullname', models.CharField(max_length=100)),
                ('intename', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('starttime', models.DateField()),
                ('location', models.CharField(max_length=10)),
                ('province', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('industry', models.CharField(max_length=10)),
                ('www', models.CharField(max_length=50)),
            ],
        ),
    ]
